parameters:
    editorial_interface.twig.extension.content.class: EzSystems\EditorialInterfaceBundle\Twig\Extension\ContentExtension

services:

    editorial_interface.twig.extension.content:
        class: %editorial_interface.twig.extension.content.class%
        arguments: [@service_container, @ezpublish.api.repository, @ezpublish.config.resolver]
        tags:
            - {name: twig.extension}

    ezpublish.twig.extension.content:
        alias: editorial_interface.twig.extension.content
